/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    keywords: Keyword;
    'rank-sheets': RankSheet;
    'keyword-requests': KeywordRequest;
    'asin-cache': AsinCache;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords".
 */
export interface Keyword {
  id: number;
  slug: string;
  keyword: string;
  title?: string | null;
  description?: string | null;
  category?: ('electronics' | 'home' | 'sports' | 'health' | 'toys' | 'automotive' | 'office' | 'other') | null;
  marketplace?: ('US' | 'UK' | 'DE') | null;
  topN?: number | null;
  isActive?: boolean | null;
  status?: ('PENDING' | 'WARMING_UP' | 'ACTIVE' | 'PAUSED' | 'ERROR') | null;
  statusReason?: string | null;
  indexable?: boolean | null;
  priority?: number | null;
  lastRefreshedAt?: string | null;
  refreshMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentGenerated?: boolean | null;
  seoScore?: number | null;
  generatedTitle?: string | null;
  generatedDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rank-sheets".
 */
export interface RankSheet {
  id: number;
  keyword: number | Keyword;
  dataPeriod: string;
  reportDate?: string | null;
  mode?: ('NORMAL' | 'LOW_DATA') | null;
  validCount?: number | null;
  readinessLevel?: ('FULL' | 'PARTIAL' | 'LOW' | 'CRITICAL') | null;
  rows:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  history?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  topAsins?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  processingStats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keyword-requests".
 */
export interface KeywordRequest {
  id: number;
  slug: string;
  keyword: string;
  category?: ('electronics' | 'home' | 'sports' | 'health' | 'toys' | 'automotive' | 'office' | 'other') | null;
  email?: string | null;
  note?: string | null;
  status?: ('NEW' | 'REVIEWED' | 'APPROVED' | 'REJECTED') | null;
  votes?: number | null;
  lastVotedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asin-cache".
 */
export interface AsinCache {
  id: number;
  asin: string;
  title?: string | null;
  brand?: string | null;
  image?: string | null;
  price?: string | null;
  paapi5Response?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('VALID' | 'STALE' | 'ERROR' | 'NOT_FOUND') | null;
  fetchedAt: string;
  expiresAt?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}